version: '3.7'
services:
  app:
    container_name: technikolor-app
    image: technikolor-app
    env_file:
      - .docker/shared_env
    build:
      target: dev
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
      context: .
      dockerfile: .docker/app/Dockerfile
    volumes:
      - .:/php/src/technikolor/app

  nginx:
    container_name: technikolor-nginx
    image: technikolor-nginx
    env_file:
      - .docker/shared_env
    build:
      context: .
      target: dev
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8080:80"
    links:
      - app
    volumes:
      - ./var/logs/nginx:/var/log/nginx
      - .:/php/src/technikolor/app

  db:
    image: postgres
    container_name: technikolor-db
    environment:
      POSTGRES_DB: technikolor
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - ./var/dbdata:/var/lib/postgresql/data
