on: [push]

name: Continuous integration

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 14

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and run app
        run: |
          docker-compose build \
            --build-arg USER_ID=$(id -u) \
            --build-arg GROUP_ID=$(id -g)

          docker-compose up -d

      - name: Copy config file and install dependencies
        run: |
          docker exec technikolor-app bash -c 'cp .env.example .env; composer install'

      - name: Run test suite
        run: docker exec technikolor-app vendor/bin/codecept run

      - name: Stop running containers
        run: docker-compose stop
